# Generated by Django 2.0.9 on 2018-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('deleted', models.BooleanField()),
                ('shower', models.BooleanField()),
                ('bathtub', models.BooleanField()),
                ('microwave', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('water_included', models.BooleanField()),
                ('heating_included', models.BooleanField()),
            ],
        ),
    ]
