# Generated by Django 2.0.9 on 2018-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20181201_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('deleted', models.BooleanField()),
                ('shower', models.BooleanField()),
                ('bathtub', models.BooleanField()),
                ('microwave', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('water_included', models.BooleanField()),
                ('heating_included', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
